/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adamasmaca;

import java.awt.event.ActionListener;
import javafx.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author ajanuser
 */
public class MainFrame extends javax.swing.JFrame {

    Oyun yenioyun;
    String Kelime="";
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        qbutton = new javax.swing.JButton();
        wbutton = new javax.swing.JButton();
        ebutton = new javax.swing.JButton();
        rbutton = new javax.swing.JButton();
        ibutton = new javax.swing.JButton();
        ubutton = new javax.swing.JButton();
        ybutton = new javax.swing.JButton();
        tbutton = new javax.swing.JButton();
        uubutton = new javax.swing.JButton();
        ggbutton = new javax.swing.JButton();
        pbutton = new javax.swing.JButton();
        obutton = new javax.swing.JButton();
        abutton = new javax.swing.JButton();
        sbutton = new javax.swing.JButton();
        dbutton = new javax.swing.JButton();
        fbutton = new javax.swing.JButton();
        kbutton = new javax.swing.JButton();
        jbutton = new javax.swing.JButton();
        hbutton = new javax.swing.JButton();
        gbutton = new javax.swing.JButton();
        iibutton = new javax.swing.JButton();
        ssbutton = new javax.swing.JButton();
        lbutton = new javax.swing.JButton();
        zbutton = new javax.swing.JButton();
        xbutton = new javax.swing.JButton();
        cbutton = new javax.swing.JButton();
        vbutton = new javax.swing.JButton();
        bbutton = new javax.swing.JButton();
        nbutton = new javax.swing.JButton();
        mbutton = new javax.swing.JButton();
        oobutton = new javax.swing.JButton();
        ccbutton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        harf1 = new javax.swing.JLabel();
        harfalt1 = new javax.swing.JPanel();
        harf2 = new javax.swing.JLabel();
        harfalt2 = new javax.swing.JPanel();
        harf3 = new javax.swing.JLabel();
        harfalt3 = new javax.swing.JPanel();
        harf4 = new javax.swing.JLabel();
        harfalt4 = new javax.swing.JPanel();
        harf5 = new javax.swing.JLabel();
        harfalt5 = new javax.swing.JPanel();
        harf6 = new javax.swing.JLabel();
        harfalt6 = new javax.swing.JPanel();
        harf7 = new javax.swing.JLabel();
        harfalt7 = new javax.swing.JPanel();
        harf8 = new javax.swing.JLabel();
        harfalt8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tahmin = new javax.swing.JTextField();
        jButton33 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        qbutton.setText("Q");

        wbutton.setText("W");

        ebutton.setText("E");

        rbutton.setText("R");

        ibutton.setText("I");

        ubutton.setText("U");

        ybutton.setText("Y");

        tbutton.setText("T");

        uubutton.setText("Ü");

        ggbutton.setText("Ğ");

        pbutton.setText("P");

        obutton.setText("O");

        abutton.setText("A");

        sbutton.setText("S");

        dbutton.setText("D");

        fbutton.setText("F");

        kbutton.setText("K");

        jbutton.setText("J");

        hbutton.setText("H");

        gbutton.setText("G");

        iibutton.setText("İ");

        ssbutton.setText("Ş");

        lbutton.setText("L");

        zbutton.setText("Z");

        xbutton.setText("X");

        cbutton.setText("C");

        vbutton.setText("V");

        bbutton.setText("B");

        nbutton.setText("N");

        mbutton.setText("M");

        oobutton.setText("Ö");

        ccbutton.setText("Ç");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(qbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ebutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ybutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ubutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ibutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(obutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ggbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uubutton)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(abutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(zbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(oobutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ccbutton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ssbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iibutton)))
                        .addGap(110, 110, 110))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {abutton, bbutton, cbutton, ccbutton, dbutton, ebutton, fbutton, gbutton, ggbutton, hbutton, ibutton, iibutton, jbutton, kbutton, lbutton, mbutton, nbutton, obutton, oobutton, pbutton, qbutton, rbutton, sbutton, ssbutton, tbutton, ubutton, uubutton, vbutton, wbutton, xbutton, ybutton, zbutton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ybutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ubutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ibutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(obutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ggbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uubutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iibutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oobutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        qbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(qbutton);   }
        });
        wbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(wbutton);   }
        });
        ebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(ebutton);   }
        });
        rbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(rbutton);   }
        });
        ibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(ibutton);   }
        });
        ubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(ubutton);   }
        });
        ybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(ybutton);   }
        });
        tbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(tbutton);   }
        });
        uubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(uubutton);   }
        });
        ggbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(ggbutton);   }
        });
        pbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(pbutton);   }
        });
        obutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(obutton);   }
        });
        abutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(abutton);   }
        });
        sbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(sbutton);   }
        });
        dbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(dbutton);   }
        });
        fbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(fbutton);   }
        });
        kbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(kbutton);   }
        });
        jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(jbutton);   }
        });
        hbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(hbutton);   }
        });
        gbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(gbutton);   }
        });
        iibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(iibutton);   }
        });
        ssbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(ssbutton);   }
        });
        lbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(lbutton);   }
        });
        zbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(zbutton);   }
        });
        xbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(xbutton);   }
        });
        cbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(cbutton);   }
        });
        vbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(vbutton);   }
        });
        bbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(bbutton);   }
        });
        nbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(nbutton);   }
        });
        mbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(mbutton);   }
        });
        oobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(oobutton);   }
        });
        ccbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonbasildi(ccbutton);   }
        });

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 346, 757, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        harf1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        harf1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        harf1.setText("A");
        jPanel2.add(harf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 49, 70));

        harfalt1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout harfalt1Layout = new javax.swing.GroupLayout(harfalt1);
        harfalt1.setLayout(harfalt1Layout);
        harfalt1Layout.setHorizontalGroup(
            harfalt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        harfalt1Layout.setVerticalGroup(
            harfalt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jPanel2.add(harfalt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 89, 49, -1));

        harf2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        harf2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        harf2.setText("A");
        jPanel2.add(harf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 13, 49, 70));

        harfalt2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout harfalt2Layout = new javax.swing.GroupLayout(harfalt2);
        harfalt2.setLayout(harfalt2Layout);
        harfalt2Layout.setHorizontalGroup(
            harfalt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );
        harfalt2Layout.setVerticalGroup(
            harfalt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jPanel2.add(harfalt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 89, -1, -1));

        harf3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        harf3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        harf3.setText("A");
        jPanel2.add(harf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 13, 49, 70));

        harfalt3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout harfalt3Layout = new javax.swing.GroupLayout(harfalt3);
        harfalt3.setLayout(harfalt3Layout);
        harfalt3Layout.setHorizontalGroup(
            harfalt3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );
        harfalt3Layout.setVerticalGroup(
            harfalt3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jPanel2.add(harfalt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 89, -1, -1));

        harf4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        harf4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        harf4.setText("A");
        jPanel2.add(harf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 13, 49, 70));

        harfalt4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout harfalt4Layout = new javax.swing.GroupLayout(harfalt4);
        harfalt4.setLayout(harfalt4Layout);
        harfalt4Layout.setHorizontalGroup(
            harfalt4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );
        harfalt4Layout.setVerticalGroup(
            harfalt4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jPanel2.add(harfalt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 89, -1, -1));

        harf5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        harf5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        harf5.setText("A");
        jPanel2.add(harf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 13, 49, 70));

        harfalt5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout harfalt5Layout = new javax.swing.GroupLayout(harfalt5);
        harfalt5.setLayout(harfalt5Layout);
        harfalt5Layout.setHorizontalGroup(
            harfalt5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );
        harfalt5Layout.setVerticalGroup(
            harfalt5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jPanel2.add(harfalt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 89, -1, -1));

        harf6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        harf6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        harf6.setText("A");
        jPanel2.add(harf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 13, 49, 70));

        harfalt6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout harfalt6Layout = new javax.swing.GroupLayout(harfalt6);
        harfalt6.setLayout(harfalt6Layout);
        harfalt6Layout.setHorizontalGroup(
            harfalt6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );
        harfalt6Layout.setVerticalGroup(
            harfalt6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jPanel2.add(harfalt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 89, -1, -1));

        harf7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        harf7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        harf7.setText("A");
        jPanel2.add(harf7, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 13, 49, 70));

        harfalt7.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout harfalt7Layout = new javax.swing.GroupLayout(harfalt7);
        harfalt7.setLayout(harfalt7Layout);
        harfalt7Layout.setHorizontalGroup(
            harfalt7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );
        harfalt7Layout.setVerticalGroup(
            harfalt7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jPanel2.add(harfalt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 89, -1, -1));

        harf8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        harf8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        harf8.setText("A");
        jPanel2.add(harf8, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 13, 49, 70));

        harfalt8.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout harfalt8Layout = new javax.swing.GroupLayout(harfalt8);
        harfalt8.setLayout(harfalt8Layout);
        harfalt8Layout.setHorizontalGroup(
            harfalt8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );
        harfalt8Layout.setVerticalGroup(
            harfalt8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jPanel2.add(harfalt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 89, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 470, 120));

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel13.setBackground(new java.awt.Color(204, 204, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel14.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel15.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jPanel16.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel17.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jPanel18.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jPanel19.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jPanel20.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jPanel21.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jPanel22.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 65, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("TAHMiN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 271, 165, 26));

        tahmin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(tahmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 303, 165, 37));

        jButton33.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton33.setText("TAMAM");
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 303, -1, -1));

        jMenu1.setText("Yeni");

        jMenuItem1.setText("Yeni Oyun");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Yeni Kullanıcı");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Çıkış");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        harfleri_goster(false);
        butonlari_goster(true);
        yenioyun=new Oyun();
        Kelime=yenioyun.KelimeyiGetir();
        for(int i=0;i<Kelime.length();i++){
            if(i==0){harfalt1.setVisible(true);}
            if(i==1){harfalt2.setVisible(true);}
            if(i==2){harfalt3.setVisible(true);}
            if(i==3){harfalt4.setVisible(true);}
            if(i==4){harfalt5.setVisible(true);}
            if(i==5){harfalt6.setVisible(true);}
            if(i==6){harfalt7.setVisible(true);}
            if(i==7){harfalt8.setVisible(true);}
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        harfleri_goster(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abutton;
    private javax.swing.JButton bbutton;
    private javax.swing.JButton cbutton;
    private javax.swing.JButton ccbutton;
    private javax.swing.JButton dbutton;
    private javax.swing.JButton ebutton;
    private javax.swing.JButton fbutton;
    private javax.swing.JButton gbutton;
    private javax.swing.JButton ggbutton;
    private javax.swing.JLabel harf1;
    private javax.swing.JLabel harf2;
    private javax.swing.JLabel harf3;
    private javax.swing.JLabel harf4;
    private javax.swing.JLabel harf5;
    private javax.swing.JLabel harf6;
    private javax.swing.JLabel harf7;
    private javax.swing.JLabel harf8;
    private javax.swing.JPanel harfalt1;
    private javax.swing.JPanel harfalt2;
    private javax.swing.JPanel harfalt3;
    private javax.swing.JPanel harfalt4;
    private javax.swing.JPanel harfalt5;
    private javax.swing.JPanel harfalt6;
    private javax.swing.JPanel harfalt7;
    private javax.swing.JPanel harfalt8;
    private javax.swing.JButton hbutton;
    private javax.swing.JButton ibutton;
    private javax.swing.JButton iibutton;
    private javax.swing.JButton jButton33;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JButton jbutton;
    private javax.swing.JButton kbutton;
    private javax.swing.JButton lbutton;
    private javax.swing.JButton mbutton;
    private javax.swing.JButton nbutton;
    private javax.swing.JButton obutton;
    private javax.swing.JButton oobutton;
    private javax.swing.JButton pbutton;
    private javax.swing.JButton qbutton;
    private javax.swing.JButton rbutton;
    private javax.swing.JButton sbutton;
    private javax.swing.JButton ssbutton;
    private javax.swing.JTextField tahmin;
    private javax.swing.JButton tbutton;
    private javax.swing.JButton ubutton;
    private javax.swing.JButton uubutton;
    private javax.swing.JButton vbutton;
    private javax.swing.JButton wbutton;
    private javax.swing.JButton xbutton;
    private javax.swing.JButton ybutton;
    private javax.swing.JButton zbutton;
    // End of variables declaration//GEN-END:variables

    private void harfleri_goster(boolean deger) {
    harf1.setVisible(deger);
    harf2.setVisible(deger);
    harf3.setVisible(deger);
    harf4.setVisible(deger);
    harf5.setVisible(deger);
    harf6.setVisible(deger);
    harf7.setVisible(deger);
    harf8.setVisible(deger);
    harfalt1.setVisible(deger);
    harfalt2.setVisible(deger);
    harfalt3.setVisible(deger);
    harfalt4.setVisible(deger);
    harfalt5.setVisible(deger);
    harfalt6.setVisible(deger);
    harfalt7.setVisible(deger);
    harfalt8.setVisible(deger);
    
    }

    private int harfara(String ara) {
        int sonuc=0;
    for(int i=0;i<Kelime.length();i++){
        if(Kelime.charAt(i)==ara.charAt(0)){sonuc++;
                 if(i==0){harf1.setVisible(true);harfalt1.setVisible(true);harf1.setText(String.valueOf(ara));}
            else if(i==1){harf2.setVisible(true);harfalt2.setVisible(true);harf2.setText(String.valueOf(ara));}
            else if(i==2){harf3.setVisible(true);harfalt3.setVisible(true);harf3.setText(String.valueOf(ara));}
            else if(i==3){harf4.setVisible(true);harfalt4.setVisible(true);harf4.setText(String.valueOf(ara));}
            else if(i==4){harf5.setVisible(true);harfalt5.setVisible(true);harf5.setText(String.valueOf(ara));}
            else if(i==5){harf6.setVisible(true);harfalt6.setVisible(true);harf6.setText(String.valueOf(ara));}
            else if(i==6){harf7.setVisible(true);harfalt7.setVisible(true);harf7.setText(String.valueOf(ara));}
            else if(i==7){harf8.setVisible(true);harfalt8.setVisible(true);harf8.setText(String.valueOf(ara));}
            }
        }
    return sonuc;
        }

    private void oyunBitir() {
        JOptionPane.showMessageDialog(this, "OYUN BİTTİ"); 

    }

    private void butonbasildi(JButton gelenbutton) {
        
        int sonuc=harfara(gelenbutton.getText());
        yenioyun.harfbulundu(sonuc);
        if(yenioyun.bulunanharf==Kelime.length())oyunBitir();
        gelenbutton.setEnabled(false);
    }

    private void butonlari_goster(boolean deger) {
        qbutton.setEnabled(deger);
        wbutton.setEnabled(deger);
        ebutton.setEnabled(deger);
        rbutton.setEnabled(deger);
        tbutton.setEnabled(deger);
        ybutton.setEnabled(deger);
        ubutton.setEnabled(deger);
        ibutton.setEnabled(deger);
        obutton.setEnabled(deger);
        pbutton.setEnabled(deger);
        ggbutton.setEnabled(deger);
        uubutton.setEnabled(deger);
        abutton.setEnabled(deger);
        sbutton.setEnabled(deger);
        dbutton.setEnabled(deger);
        fbutton.setEnabled(deger);
        gbutton.setEnabled(deger);
        hbutton.setEnabled(deger);
        jbutton.setEnabled(deger);
        kbutton.setEnabled(deger);
        lbutton.setEnabled(deger);
        ssbutton.setEnabled(deger);
        iibutton.setEnabled(deger);
        zbutton.setEnabled(deger);
        xbutton.setEnabled(deger);
        cbutton.setEnabled(deger);
        vbutton.setEnabled(deger);
        bbutton.setEnabled(deger);
        nbutton.setEnabled(deger);
        mbutton.setEnabled(deger);
        oobutton.setEnabled(deger);
        ccbutton.setEnabled(deger); 
    }
}



/*
for(int i=0;i<Kelime.length();i++){
            if(i==0){harf1.setVisible(true);harfalt1.setVisible(true);harf1.setText(String.valueOf(Kelime.charAt(i)));}
            if(i==1){harf2.setVisible(true);harfalt2.setVisible(true);harf2.setText(String.valueOf(Kelime.charAt(i)));}
            if(i==2){harf3.setVisible(true);harfalt3.setVisible(true);harf3.setText(String.valueOf(Kelime.charAt(i)));}
            if(i==3){harf4.setVisible(true);harfalt4.setVisible(true);harf4.setText(String.valueOf(Kelime.charAt(i)));}
            if(i==4){harf5.setVisible(true);harfalt5.setVisible(true);harf5.setText(String.valueOf(Kelime.charAt(i)));}
            if(i==5){harf6.setVisible(true);harfalt6.setVisible(true);harf6.setText(String.valueOf(Kelime.charAt(i)));}
            if(i==6){harf7.setVisible(true);harfalt7.setVisible(true);harf7.setText(String.valueOf(Kelime.charAt(i)));}
            if(i==7){harf8.setVisible(true);harfalt8.setVisible(true);harf8.setText(String.valueOf(Kelime.charAt(i)));}
        }
*/